import Head from 'next/head'
import styles from '../styles/modules/Home.module.scss'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container mx-auto bg-blue-300">
				<h3>Featured Products</h3>
				<ul className="grid grid-cols-2 gap-2">
					<li>Hello</li>
				</ul>
			</div>
		</div>
	)
}
